name: cura_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.3.0=h27087fc_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.0.9=py310hd8f1fbe_7
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.9.9=h06a4308_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.15.0=py310h0fdd8cc_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h9033bb2_6
  - dbus=1.16.2=h3c4dab8_0
  - docker-pycreds=0.4.0=py_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=5.0.1=h964e5f1_2
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.59.2=py310h3406613_0
  - freetype=2.13.3=h4a9f257_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - grpcio=1.71.0=py310h7053be5_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_hbbce691_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=6_ha36c22a_netlib
  - libclang13=14.0.6=default_h9986a30_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.5.147=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.84.2=h37c7471_0
  - libgomp=15.1.0=h767d61c_5
  - libgrpc=1.71.0=he753a82_0
  - libiconv=1.18=h3b78370_2
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=6_ha36c22a_netlib
  - liblapacke=3.9.0=6_ha36c22a_netlib
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.67.0=had1ee68_0
  - libnpp=11.7.4.75=0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjpeg=11.8.0.2=0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h501fc15_0
  - libre2-11=2024.07.02=hba17884_3
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.21.0=hd590300_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=hfdd30dd_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.44.0=py310h0070a79_2
  - lmdb=0.9.31=hd590300_1
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.9=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h89163eb_1
  - matplotlib=3.10.6=py310hff52083_1
  - matplotlib-base=3.10.6=py310hfde16b3_1
  - minizip=4.0.3=hf59b114_0
  - mkl=2020.2=256
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - nettle=3.6=he412f7d_0
  - nspr=4.37=h29cc59b_0
  - nss=3.115=hc3c8bcf_0
  - numba=0.61.2=py310h8648a56_1
  - numpy=1.26.4=py310hb13e2d6_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.5=h389dcaa_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=1.5.3=py310h9b08913_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hcad00b1_0
  - pillow=11.1.0=py310hac6e08b_1
  - pip=25.2=pyhc872135_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - protobuf=5.29.3=py310hcba5963_0
  - psutil=7.0.0=py310h7c4b9e2_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py310hbcd0ec0_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.7.2=py310ha2c6bb1_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - qhull=2020.2=h434a139_5
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtshadertools=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebengine=6.7.3=h7abb84b_0
  - qtwebsockets=6.7.3=h7934f7d_1
  - re2=2024.07.02=h9925aae_3
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.14.1=py310ha3fb0e1_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sentry-sdk=2.37.1=pyhd8ed1ab_0
  - setproctitle=1.3.6=py310ha75aee5_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - sqlite=3.50.2=hb25bd0a_1
  - statsmodels=0.14.5=py310haaf2d95_0
  - svt-av1=1.1.0=h27087fc_1
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310h6c63255_2
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.13.1=py310_cu117
  - torchvision=0.14.1=py310_cu117
  - tornado=6.5.2=py310h7c4b9e2_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wandb=0.21.1=py310hdfeec95_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.2=h8a70e8d_1
prefix: /home/guanghere/anaconda3/envs/cura_env
